### ISSUE TITLE
Error when loading dataset

### ISSUE THREAD

**Issue by dearmaker** [nikita68/TransportPlanningDataset#2]
Dear Professor:

I meet with "In valid data stream" when loading the pbz2 file. I did not find a good way to solve it. Could you please give me more instructions on the data file format you used? Or, can you provide the data in a more widely used data format?

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
[e:\whrProgram\TransportPlanningDataset-main\3_regression\2_example_private_transport_regression.py](file:///E:/whrProgram/TransportPlanningDataset-main/3_regression/2_example_private_transport_regression.py) in line 18
     [16](file:///e%3A/whrProgram/TransportPlanningDataset-main/3_regression/2_example_private_transport_regression.py?line=15) # First load in data
     [17](file:///e%3A/whrProgram/TransportPlanningDataset-main/3_regression/2_example_private_transport_regression.py?line=16) with bz2.BZ2File("1_data_regression.pbz2", 'rb') as handle:
---> [18](file:///e%3A/whrProgram/TransportPlanningDataset-main/3_regression/2_example_private_transport_regression.py?line=17)     data_dic = pickle.load(handle)

File [d:\PROGRAM\anaonda\envs\py-edge\lib\bz2.py:155](file:///D:/PROGRAM/anaonda/envs/py-edge/lib/bz2.py:155), in BZ2File.peek(self, n)
    [151](file:///d%3A/PROGRAM/anaonda/envs/py-edge/lib/bz2.py?line=150) self._check_can_read()
    [152](file:///d%3A/PROGRAM/anaonda/envs/py-edge/lib/bz2.py?line=151) # Relies on the undocumented fact that BufferedReader.peek()
    [153](file:///d%3A/PROGRAM/anaonda/envs/py-edge/lib/bz2.py?line=152) # always returns at least one byte (except at EOF), independent
    [154](file:///d%3A/PROGRAM/anaonda/envs/py-edge/lib/bz2.py?line=153) # of the value of n
--> [155](file:///d%3A/PROGRAM/anaonda/envs/py-edge/lib/bz2.py?line=154) return self._buffer.peek(n)

File [d:\PROGRAM\anaonda\envs\py-edge\lib\_compression.py:68](file:///D:/PROGRAM/anaonda/envs/py-edge/lib/_compression.py:68), in DecompressReader.readinto(self, b)
     [66](file:///d%3A/PROGRAM/anaonda/envs/py-edge/lib/_compression.py?line=65) def readinto(self, b):
     [67](file:///d%3A/PROGRAM/anaonda/envs/py-edge/lib/_compression.py?line=66)     with memoryview(b) as view, view.cast("B") as byte_view:
---> [68](file:///d%3A/PROGRAM/anaonda/envs/py-edge/lib/_compression.py?line=67)         data = self.read(len(byte_view))
     [69](file:///d%3A/PROGRAM/anaonda/envs/py-edge/lib/_compression.py?line=68)         byte_view[:len(data)] = data
     [70](file:///d%3A/PROGRAM/anaonda/envs/py-edge/lib/_compression.py?line=69)     return len(data)

File [d:\PROGRAM\anaonda\envs\py-edge\lib\_compression.py:103](file:///D:/PROGRAM/anaonda/envs/py-edge/lib/_compression.py:103), in DecompressReader.read(self, size)
    [101](file:///d%3A/PROGRAM/anaonda/envs/py-edge/lib/_compression.py?line=100)     else:
    [102](file:///d%3A/PROGRAM/anaonda/envs/py-edge/lib/_compression.py?line=101)         rawblock = b""
--> [103](file:///d%3A/PROGRAM/anaonda/envs/py-edge/lib/_compression.py?line=102)     data = self._decompressor.decompress(rawblock, size)
    [104](file:///d%3A/PROGRAM/anaonda/envs/py-edge/lib/_compression.py?line=103) if data:
    [105](file:///d%3A/PROGRAM/anaonda/envs/py-edge/lib/_compression.py?line=104)     break

OSError: Invalid data stream

**Comment by nikita6187** [comment]
Hello,

Which package versions are you using? 

EDIT: some more tips on what to check:
1. Is the correct path being used?
2. Are you loading all packages before?



I just tried this out with a blank environment and it seems to be working.

Just FYI, I ran the following commands to install the environment (Python 3.11.6):

```
python3 -m venv test_env
source test_env/bin/activate
pip install numpy
pip install torch_geometric
pip install torch
```

And here is the resulting package list that I am using:

```
Package                  Version
------------------------ ----------
certifi                  2023.7.22
charset-normalizer       3.3.1
filelock                 3.13.0
fsspec                   2023.10.0
idna                     3.4
Jinja2                   3.1.2
joblib                   1.3.2
MarkupSafe               2.1.3
mpmath                   1.3.0
networkx                 3.2.1
numpy                    1.26.1
nvidia-cublas-cu12       12.1.3.1
nvidia-cuda-cupti-cu12   12.1.105
nvidia-cuda-nvrtc-cu12   12.1.105
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu12        8.9.2.26
nvidia-cufft-cu12        11.0.2.54
nvidia-curand-cu12       10.3.2.106
nvidia-cusolver-cu12     11.4.5.107
nvidia-cusparse-cu12     12.1.0.106
nvidia-nccl-cu12         2.18.1
nvidia-nvjitlink-cu12    12.3.52
nvidia-nvtx-cu12         12.1.105
pip                      23.2.1
psutil                   5.9.6
pyparsing                3.1.1
requests                 2.31.0
scikit-learn             1.3.2
scipy                    1.11.3
setuptools               65.5.0
sympy                    1.12
threadpoolctl            3.2.0
torch                    2.1.0
torch_geometric          2.4.0
tqdm                     4.66.1
triton                   2.1.0
typing_extensions        4.8.0
urllib3                  2.0.7

```

And here is the code:

```

import bz2
import pickle


# First load in data
with bz2.BZ2File("1_data_regression.pbz2", 'rb') as handle:
    data_dic = pickle.load(handle)


print(data_dic.keys())


```

**Comment by RaisssHab** [comment]
Hello! Thanks for your participation.

I tried it in Google Colab with Python version 3.10, and it doesn't work there. The versions of course differ from what you listed here because you're using the version 3.11. Nevertheless, the last commit was made in February, 2022, and Python 3.11 was released in October, 2022, so it is probably possible to load the file with Python 3.10.

I've noticed the absence of nvidia packages on Python 3.10 when installing. 

Here's the code I use to upgrade the Python version basing on https://stackoverflow.com/questions/68657341/how-can-i-update-google-colabs-python-version:
```
#**Add python version you wish** to list
!sudo apt-get update -y
!sudo apt-get install python3.11
from IPython.display import clear_output
clear_output()
!sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 1

# Choose one of the given alternatives:
!sudo update-alternatives --config python3

# This one used to work but now NOT(for me)!
# !sudo update-alternatives --config python

# Check the result
!python3 --version

# Attention: Install pip (... needed!)
!sudo apt install python3-pip

# install pip for new python
!sudo apt-get install python3.11-distutils
!wget https://bootstrap.pypa.io/get-pip.py
!python get-pip.py

# credit of these last two commands blongs to @Erik
# install colab's dependencies
!python -m pip install ipython ipython_genutils ipykernel jupyter_console prompt_toolkit httplib2 astor

# link to the old google package
!ln -s /usr/local/lib/python3.10/dist-packages/google \
       /usr/local/lib/python3.11/dist-packages/google
```

On install part, there's a warning to restart the runtime. If to ignore it and try to import libraries, it fails on the line "from torch_geometric.data import DataLoader" saying that torch_geometric isn't available. When attempting to restart the runtime, there's an issue with it which doesn't allow to restart. 

Here's the notebook (with type changed to txt to be able do upload it here):
[2_example_private_transport.txt](https://github.com/nikita6187/TransportPlanningDataset/files/13208356/2_example_private_transport.txt)

**Comment by nikita6187** [comment]
Unfortunately I've never used Colab and packages there, but I don't think the nvidia packages or Python version are critical. 

I think the critical part is the torch_geometric import.  

Checkout their website for correct installation:  https://pytorch-geometric.readthedocs.io/en/latest/install/installation.html
I also found this script which might help: https://gist.github.com/ameya98/b193856171d11d37ada46458f60e73e7

Let me know if the error still persists after pytorch geometric installation!

**Comment by RaisssHab** [comment]
Okay, the problem was that the dataset was corrupted and weighted 1 KB instead of 100 MBs. Sorry for disturbance and thanks with the help!
